- project:
    templates:
      - check-requirements
      - openstack-python-jobs-neutron
      - openstack-python3-ussuri-jobs-neutron
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
    check:
      jobs:
        - networking-generic-switch-tempest-dlm
        - networking-generic-switch-tempest-dlm-python2
        - ironic-tempest-ipa-wholedisk-direct-tinyipa-multinode:
            irrelevant-files:
              - ^(test-|)requirements.txt$
              - ^setup.cfg$
        # NOTE(rpittau): temp disabling job until all changes
        # for ussuri are completed
        - ironic-grenade-dsvm-multinode-multitenant:
            voting: false
        - openstack-tox-lower-constraints
    gate:
      queue: networking-generic-switch
      jobs:
        - networking-generic-switch-tempest-dlm
        - networking-generic-switch-tempest-dlm-python2
        - ironic-tempest-ipa-wholedisk-direct-tinyipa-multinode:
            irrelevant-files:
              - ^(test-|)requirements.txt$
              - ^setup.cfg$
        # NOTE(rpittau): temp disabling job until all changes
        # for ussuri are completed
        # - ironic-grenade-dsvm-multinode-multitenant
        - openstack-tox-lower-constraints
